### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by byaura** [dumbasPL/csgo-checker#3]
Hey I like this project but there are somethings missing.
1. It would be better to see an option to mass delete all the accounts since to delete accounts I have to go to the accounts.json file and delete everything
2. See the date of the last played match would be also a great feature to keep track on when the account will lose it's rank or whatever
3. Add an image to the rank (???)
4. Sort by lvl, Prime or by ban/error would also be a great feature to have.
Keep the great work!

**Comment by dumbasPL** [comment]
> It would be better to see an option to mass delete all the accounts since to delete accounts I have to go to the accounts.json file and delete everything

no idea why someone would need that but I will try to implement it next time I work on an update.

> See the date of the last played match would be also a great feature to keep track on when the account will lose it's rank or whatever

That is a cool idea for sure. Do you by any chance know the exact time it takes for a rank to expire?

> Add an image to the rank (???)

Will be done when I finally decide to do a UI overhaul. The UI is very messy in its current state and needs to be redone.

> Sort by lvl, Prime or by ban/error would also be a great feature to have.
Keep the great work!

Same as nr 3, is already a thing I thought of myself and will be done when I decide to redo the UI.

**Comment by byaura** [comment]
I know no one cares about my first idea but idk someone may need it.
It takes exactly 30 days with no played matches for a rank to expire.

**Comment by dumbasPL** [comment]
Implemented in 1d879e60d6f2c4ea1049ed541bb36819fb6f7fd5
If you have any issues with the new update please create a new issue.
