### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by xXYZYXx** [dumbasPL/csgo-checker#5]
First of all sry that i abuse this function but this feature is needed a friend of mine coded it into every version until now and it is better if it is onboard so okay it is nice if u can add a text field with shared secret to the acc add so that an account with steam guard mobile dont need the code everytime when reload

**Comment by dumbasPL** [comment]
if your friend already implemented it, tell him to make a pull request, It will help.  
This is a feature I already planned to do for a while but never got to it.  
I probably would want to add encryption first before storing 2fa secrets

**Comment by dumbasPL** [comment]
added in b5fa81fa556e31a46582e832f6048eab495ce74d
If you experience any issues please make a new Issue
