### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by JoKerIsCraZy** [dumbasPL/csgo-checker#7]
Hey is there a way to make an Portable Version?

-Export all accounts dont export the shared secret key / import

-Add an button to Login directly to an account

**Comment by dumbasPL** [comment]
For now you can use the [`--user-data-dir`](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md) switch to change the location of the user data folder.

you can put a bat file like this
```batch
"C:\Users\admin\AppData\Local\Programs\csgo-checker\CSGO account checker.exe" --user-data-dir=%~dp0
```
and it will store the data in the same folder as the bat file.

**Comment by dumbasPL** [comment]
fixed in https://github.com/dumbasPL/csgo-checker/releases/tag/v1.3.0
